project_id = "vlcrqrmqghskrdhhsgqt"

[functions.chat-with-anthropic]
verify_jwt = false
import_map = "./import_map.json"

[functions.chat-with-openai]
verify_jwt = false

[functions.update-profile]
verify_jwt = false