export const prepareRaceData = (race: any, raceDateTime: string) => {
  return {
    off_time: raceDateTime,
    course: race.course,
    race_name: race.race_name,
    region: race.region,
    race_class: race.race_class,
    age_band: race.age_band,
    rating_band: race.rating_band,
    prize: race.prize,
    field_size: Number(race.field_size) || 0,
    race_id: race.race_id,
    course_id: race.course_id,
    distance_round: race.distance_round,
    distance: race.distance,
    distance_f: race.distance_f,
    pattern: race.pattern,
    type: race.type,
    going_detailed: race.going_detailed,
    rail_movements: race.rail_movements,
    stalls: race.stalls,
    weather: race.weather,
    going: race.going,
    surface: race.surface,
    jumps: race.jumps,
    big_race: race.big_race,
    is_abandoned: race.is_abandoned,
  };
};